server:
  port: ${PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true  
        
greeting:
  displayFortune: true
  from: default
  secret: default        